### ISSUE TITLE
Request for documentation : exploded view & assembly guide

### ISSUE THREAD

**Issue by V-Roger** [edgarkech/scalable_field_camera#9]
# Request for documentation

Hi, **thanks for the great work**! I'm halfway through printing this, and the parts look great.

A greatly helpful addition to the already very detailed `READMEs` would be an exploded view of the camera and/or an assembly guide.

I'm pretty sure I could figure it out by myself as the design is rather smart, but mistakes are probable without the proper assembly instructions.

Thank you so much again, can't wait to expose some 4x5 !

**Comment by edgarkech** [comment]
Hi Virgil,
thanks for your message.
Well, you know I used this project to switch from TinkerCAD to OpenSCAD. For the basic designing skills (single parts, but also making a design parametric) I suppose you can call this transition successful, but I didn't dive enough into it yet to create assemblies and/or exploded views. 
Also, my intention was just a pure, personal project (besides the large format photography as "main" hobby"). Before releasing the design, I didn't spend (m)any thoughts on sourcing problems or documentation... 
Since then, my personal priorities have also shifted a bit, so I am currently quite short of time (and honestly motivation) for overall/extensive documentation work.
Nevertheless, I'll try to answer specific questions.... 

Edgar

**Comment by V-Roger** [comment]
Hey Edgar!

Thanks for the reply, I get it it's a very time-consuming project :D

If I fall upon specific problems (as I'm not done printing yet I'm not sure what they might be), I'll be sure to ask you.

On a more open-source front, would you mind if I take it upon myself to create the exploded view and / or assembly guide ? Would be glad to help and give back to the project :)
If you're OK with it I'll shoot a PR this way when I'm done building mine.

Take care !

**Comment by edgarkech** [comment]
> On a more open-source front, would you mind if I take it upon myself to create the exploded view and / or assembly guide ? Would be glad to help and give back to the project :)

... that's one reason why I switched over from thingiverse to github ;-)
Just let me know if you have any issues with permissions or other administrative stuff, so I can (hopefully) set it up.
